zingolabs/zingolib

README.md

I added a little thing in the readme:
- cd zingo
- install protobuf-compiler

cd zingo added to readme

---

README.md

change readme to suggest 127.0.0.1 in zcashd config

---

cli/src/main.rs

Solves #39 .
`zingo-cli`'s regtest mode needs to be run in its own worktree, to properly find the conf files and log to the correct locations.
This is a more robust (and properly working) adjustment.

fixed regtest mode git sanity check

---

regtest/bin/.gitignore
regtest/datadir/.gitignore
regtest/logs/.gitignore

Add .gitignore files for regtest logs/bin/data
Nice to have a clean HEAD

.gitignore for regtest

---

cli/src/lib.rs
lib/src/lib.rs

Fixes #21
Note the refactor of `ZingoConfig` will require refactor in mobile.. which I am looking into now.

create_on_data_dir is simply a public fn in zingolib

---

cli/src/main.rs
lib/src/blaze/trial_decryptions.rs
lib/src/wallet.rs
lib/src/wallet/data.rs
lib/src/wallet/keys.rs
lib/src/wallet/keys/orchard.rs

We need a low-noise environment to develop in.  This commit simply addresses each compiler warning.

fix warnings

---

cli/src/main.rs

Chasing #34 #35 #36!
It's also been discussed that using `tokio` and async / await is the preferred path forward.

Regtest Tokio, sleepless launch, graceful shutdown

---

Cargo.lock
cli/src/lib.rs
config/Cargo.toml
config/src/lib.rs
lib/src/blaze/fetch_compact_blocks.rs
lib/src/blaze/syncdata.rs
lib/src/commands.rs
lib/src/lib.rs
lib/src/lightclient.rs
lib/src/lightclient/test_server.rs
lib/src/lightclient/tests.rs
lib/src/wallet/keys/sapling.rs

This adds a changeserver command!

Move server to RwLock, allow for ChangeServer command

---

cli/src/regtest.rs
regtest/README.md

Follow-up to #70 merge-in.
#71 issue is appearing on this branch as well.

patch data vs datadir, cleanup

---

cli/src/regtest.rs
regtest/README.md

Quick updates to README and embellished error messages.

update regtest README and error messages

---

cli/Cargo.toml
cli/examples/scenarios.rs
cli/src/lib.rs
cli/src/main.rs
cli/src/regtest.rs

Simple port from macro to fn, and addition of first example scenario.
You can run examples like this:
`cargo test --example scenarios`

Arg macro to fn

---

Cargo.lock
cli/Cargo.toml
cli/examples/scenarios.rs
cli/src/lib.rs
cli/src/main.rs
cli/src/regtest.rs

This should land second after the port from the macro to the function.

Upgrade clap

---

lib/src/blaze/fetch_full_transaction.rs
lib/src/blaze/trial_decryptions.rs
lib/src/wallet/traits.rs

We have no benchmarks, but this  _should_ be a small performance improvement.. I did clone a couple things, so it's possible that adds more of an overhead than the batching gets rid of.

Batch decryption

---

cli/src/lib.rs

A reasonable place to start writing scenarios...

Factor startup into cli runner method

---

cli/examples/scenarios.rs
cli/src/lib.rs
cli/src/main.rs
config/src/lib.rs
lib/src/lib.rs

Forbid unsafe code

---

cli/Cargo.toml
cli/src/regtest.rs
cli/tests/data/mod.rs
cli/tests/integration_tests.rs

create framework and tests for experimenting with cross version compatiblity

start cross version testing

---

Cargo.lock
cli/Cargo.toml
cli/tests/integration_tests.rs
cli/tests/utils/mod.rs
lib/src/lightclient.rs

This is much cleaner, and more useful.

Refactor cross version

---

cli/src/lib.rs
cli/src/main.rs

This structure was largely my own construction, so I thought it would be reasonable to factor it into a more coherent flow.
The struct that is set up as a function of the command line arguments (as parsed by clap) is now called a ConfigTemplate.  Its constructor is now named "fill".  The 'filled' config template is now passed between the operational functions of the library.
This decomposes configuration from other tasks (like launch).  I hope this is more understandable.

I was having difficulty understanding the structure of CLI launch

---

.github/workflows/rust.yml

@juanky201271 how's this look?

try stable per Juanky's suggestion for workflow rust toolchain

---

lib/src/blaze/block_witness_data.rs
lib/src/blaze/fetch_compact_blocks.rs
lib/src/blaze/sync_status.rs
lib/src/blaze/syncdata.rs
lib/src/blaze/trial_decryptions.rs
lib/src/lightclient.rs
lib/src/lightclient/test_server.rs
lib/src/lightclient/tests.rs
lib/src/wallet.rs

Before we can land this we need to confirm that @juanky201271 can get the runtime logs in Android Studio.
I tested that on the command line setting the RUST_LOG env variable as follows:
`RUST_LOG=zingolib=debug`
gave me the same information that I was getting via `info!` before this change.
I don't know exactly how the logs are being accessed in AS so, I don't know how/where to configure that variable.

make sync status align

---

cli/src/lib.rs
lib/src/blaze/sync_status.rs
lib/src/blaze/syncdata.rs
lib/src/lightclient.rs
lib/src/lightclient/tests.rs

This feature, saves per-batch processed.   I am not entirely clear on _when_ this is a good idea!

Save on sync

---

cli/src/lib.rs
cli/src/regtest.rs
cli/tests/integration_tests.rs
cli/tests/utils/mod.rs
config/src/lib.rs
lib/src/lib.rs
lib/src/lightclient.rs
lib/src/wallet.rs

Let's get this implemented next!

Interrupt sync

---

lib/src/blaze/block_witness_data.rs
lib/src/blaze/sync_status.rs
lib/src/commands.rs

This adds a `witnesses_updated` metric to sync_status!

Witness update in sync status

---

lib/src/blaze/block_witness_data.rs
lib/src/blaze/sync_status.rs
lib/src/blaze/trial_decryptions.rs
lib/src/blaze/update_notes.rs
lib/src/commands.rs
lib/src/wallet/data.rs
lib/src/wallet/traits.rs
lib/src/wallet/transactions.rs

Fix syncstatus display of update_witnesses

---

zingolib/src/lightclient.rs

We need to discuss this before letting it integrate into mobile.

reduce batch size by 10x

---

zingolib/src/commands.rs
zingolib/src/lightclient.rs

This exposes interruption so that consumers can toggle it.

Publish interrupt

---

zingo-memo/src/lib.rs
zingocli/Cargo.toml
zingocli/tests/integration_tests.rs
zingocli/tests/utils/mod.rs
zingolib/Cargo.toml
zingolib/src/lightclient.rs
zingolib/src/lightclient/tests.rs
zingolib/src/wallet.rs
zingolib/src/wallet/transactions.rs

I clipped out the unspent_note test and test upgrades when I force pushed to dev.

Recover test upgrade

---

zingolib/src/wallet.rs

Let's consider this PR in the context of #282 what can we learn from these observations?

match statement directed to wrong arm, fixed

---

zingolib/src/lightclient.rs
zingolib/src/wallet.rs

I haven't made any of the functional changes I'd like to...including adding some more user-specification for what privacy leaks are allowed (or manual pool specification, even)...but this is certainly tidier, and will be easier to work with.

Improve note selection

---

zingocli/src/lib.rs
zingolib/src/lib.rs

This needs one change in zingo-mobile to adapt to the new type, which I will open as a zingo-mobile PR

We no longer panic when failing to connect to server on blockheight request

---

zingocli/src/lib.rs

Chain command line flag

---

zingolib/src/commands.rs
zingolib/src/lightclient.rs
zingolib/src/wallet/keys/unified.rs

This PR includes the ViewKeyExport code and an additional `get_birthday` API.

Viewkey export

---

zingolib/src/commands.rs
zingolib/src/lightclient.rs

exportufvk now returns an object including birthday, and we once again always calculate the birthday the same way.

Add birthday to exportufvk, and align different methods of getting birthday

---

.gitignore
zingocli/src/lib.rs

in zingo-cli. for convenience.

added default wallet dir

---

zingocli/tests/integration_tests.rs
zingolib/src/blaze/update_notes.rs
zingolib/src/wallet.rs
zingolib/src/wallet/data.rs
zingolib/src/wallet/traits.rs
zingolib/src/wallet/transactions.rs

Note that three tests are now failing at an explicit todo! macro invocation. I believe this to be the pre-existing error, that's now failing early instead of silently doing the wrong thing.

Mark txid nf spent error

---

zingolib/src/lightclient.rs

This makes the start_sync function more readable and restricts the definition of a "fresh" wallet to exclude wallets that previously had sapling value commitments.
Here're questions:
Do we have a buggy edge case more generally where a wallet is pre-orchard, but has sapling spends?
Do we have a test of a wallet that was initialized pre-orchard and had funds, and is then synced post-orchard?

define empty_trees fn to make start_sync readable, and more correct

---

Cargo.lock
Cargo.toml

@Oscar-Pepper this might fix your missing dependency issue.

update to depend on release-lwsdk-2.0.0

---

zingolib/src/wallet.rs

Refactor add outputs to builder

---

zingolib/src/wallet.rs

This PR sums up my work thus far on `refactoring send_to_addresses_inner`.   Merging it should close any preceding PRs.

Break build out

---

zingo-testutils/src/lib.rs
zingocli/tests/integration_tests.rs
zingolib/src/commands.rs
zingolib/src/lightclient.rs
zingolib/src/wallet.rs

This allows for wallets to be created with a mnemonic and an explicit (non-zero) account index.

Support non-zero account indexes

---

zingo-testutils/src/lib.rs

A new scenario for testing sapling balance added in `zingo-testutils`

Adding a new scenario in zingo-testutils for sapling balance

---

zingolib/src/lightclient.rs
zingolib/src/wallet/data.rs

ran cargo nextest --all-features locally

added unconfirmed to summaries

---

zingolib/src/blaze/sync_status.rs

this improves cli experience, especially around finding transaction heights while syncking

upgrade cli syncing diagnostic

---

zingocli/tests/integration_tests.rs
zingolib/src/blaze/fetch_full_transaction.rs
zingolib/src/grpc_connector.rs
zingolib/src/lightclient.rs
zingolib/src/wallet.rs
zingolib/src/wallet/data.rs
zingolib/src/wallet/transactions.rs

I'm hopeful this will fix #613, or at least shed some light on it!

Add marking of unconfirmed_spent

---

zingolib/src/blaze/trial_decryptions.rs
zingolib/src/blaze/update_notes.rs

This should fix our sync speed regression!

Fix unneeded calls to fetch_full_transaction

---

darkside-tests/tests/tests.rs
integration-tests/tests/integrations.rs
zingocli/src/lib.rs

display no chain name instead of panicking in cli when connection drops during info call

---

zingolib/src/blaze/update_notes.rs

may fix multithreading sync errors

deduplicated write unlocking

---

zingolib/src/blaze/fetch_full_transaction.rs
zingolib/src/error.rs
zingolib/src/lightclient.rs
zingolib/src/wallet/data.rs
zingolib/src/wallet/transactions.rs

in test mode, error handling will panic

Error test panic

---

.gitignore

added zingocli wallets to gitignore
