zingolabs/zingolib

- README.md
- cli/src/lib.rs
- cli/src/main.rs
- cli/src/version.rs
- config/src/lib.rs
- lib/src/lightclient/lightclient_config.rs
- lib/src/wallet/keys.rs
WIP!
Following up on [an older issue](https://github.com/zingolabs/zingolib_original/issues/85).
Solves #6 with first commit. 
<strike>Currently a non-functional flag that is recognized when running the compiled binary (ex, `./target/release/zingo-cli --regtest`).</strike>
> WIP : Add regtest mode

- Cargo.lock
- lib/Cargo.toml
- lib/src/lib.rs
- lib/src/lightclient.rs
- lib/src/lightclient/test_server.rs
- lib/src/lightclient/tests.rs
- lib/src/test_framework.rs
- lib/src/test_framework/macros.rs
- lib/src/wallet.rs
Scenario tests require a test server, which should be shutdown in all cases (except for tests of the scenario framework itself).
This is an experiment with the use of a macro to bind setup-and-teardown for this kind of test.
> Scenario macro expt

- lib/src/blaze/trial_decryptions.rs
Fixes the failure to sync pre-orchard-activation-height blocks introduced by fetching/storage of orchard anchors.
> Allow sync of pre-orchard activation blocks

- lib/src/lightclient.rs
- lib/src/wallet.rs
- lib/src/wallet/keys.rs
I assume this means that @juanky201271 does not use `Keys::read` directly from `zingo-mobile`, and that this is therefore a safe update.
> Update Serialization Version Naming Scheme

- .helix/languages.toml
- cli/Cargo.toml
- cli/src/regtest.rs
- cli/tests/data/mod.rs
- cli/tests/integration_tests.rs
- cli/tests/utils/mod.rs
- lib/src/wallet/keys/unified.rs
To run the cross_version test:
Build the `c9a2f03c5e9cfd60f955a411e6a414fd6d7db42c` version of `zingolib` 
in "release" mode and link the binary from the `regtest/bin` directory of the test-code repo..  i.e. this feature's version of the code.
`cargo test --release --features cross_version cross_compat`
> Cross version

- cli/tests/integration_tests.rs
I think we should just update this test expectation, because the `zcash-cli` output is only exposed to us as part of our test-framework.   In production `zingolib` talks to `lightwalletd`.
> reverse order of bytes in zcash-cli output

- cli/tests/integration_tests.rs
- config/src/lib.rs
- lib/src/lightclient/test_server.rs
- lib/src/lightclient/tests.rs
- lib/src/wallet.rs
Setting the buffer to 0 causes us an attempt to fetch orchard anchors from above the chain. It seems this number is 1-indexed. I'm not sure what's happening with that, exactly. Needs to be investigated.
> Set reorg buffer to 1

- lib/src/lightclient/test_server.rs
- lib/src/lightclient/tests.rs
Pros:
* slightly faster test
* simpler test framework
Cons:
* skipping the HTTP server case in test
> rm test_server http support, tests are now only https

- zingocli/tests/integration_tests.rs
- zingocli/tests/utils/mod.rs
- zingolib/src/test_framework/macros.rs
I think this verifies that all the 7 possible clearances of lower-protocol pools into orchard for self-spends achieves the correct balances.
> Verify pool upgrade paths

- zingocli/src/lib.rs
- zingoconfig/src/lib.rs
- zingolib/src/grpc_connector.rs
This checks that the CLI has been invoked in interactive mode before printing informational strings on startup.
Non-Interactive invocations will have not initial output.
Also removes dbg! call dangling when creating a GRPC connection and removes dbg call from GrpcConnecto constructor
Closes #267
> [#267] debug output leaking into CLI non-interactive calls

- Cargo.lock
- zingocli/Cargo.toml
- zingocli/tests/integration_tests.rs
- zingolib/src/blaze/fetch_full_transaction.rs
- zingolib/src/lightclient.rs
- zingolib/src/lightclient/tests.rs
- zingolib/src/wallet/data.rs
@zancas This PR should fix the duplicate transaction bug, could you take a look at the test here? I'm not sure it's comprehensive enough, and I've changed the way that transactions are displayed (transparent sends-to-self now show up in metadata, and when we detect transparent pool stuff we check to see if we already have the transaction listed...but we seem to already have everythind handled in that case, which I'm suspicious of.
> Fix duplicate transaction

- zingocli/tests/integration_tests.rs
- zingolib/src/commands.rs
- zingolib/src/lightclient.rs
- zingolib/src/wallet.rs
@juanky201271 when this lands, the command `shield` will now need an argument of 'transparent', 'sapling', or 'all'. I think we want 'all' to be what the shield button does...once we have basic/advanced mode, that's something we'll want to allow to be configurable in advanced mode.
> retool shield command to shield sapling and/or transparent pools with argument

- README.md
The `patch.crates-io` section from Cargo.toml no longer exists.
> Drop obsolete paragraph from README

- zingoconfig/src/lib.rs
- zingolib/src/lib.rs
This allows the zingolib to be used by other applications without them having to share a wallet file.
> Make persisted file names configurable

- .editorconfig
This helps ensure all editors will handle the code files the same way.
For example, my editor was inserting tabs into .rs file which clearly use spaces. By adding this file, the editor always uses spaces for this repo, regardless of my editor's default.s
> Add .editorconfig to repo

- zingocli/tests/darkside/tests.rs
- zingolib/src/commands.rs
- zingolib/src/lightclient.rs
Prior to this, the rather predictable data was returned as a JSON object, which made programmatic extraction uncertain to succeed and runtime and largely undocumented. With this, a caller gets a struct with predictable fields.
> Produce strongly typed struct as sync result

- zingolib/src/commands.rs
- zingolib/src/lightclient.rs
Fixes #463
Sample zingo-cli output after the fix:
```
(main) Block:2214445 (type 'help') >> sync
{
"result": "success",
"latest_block": 2214445,
"total_blocks_synced": 0
}
(main) Block:2214445 (type 'help') >> rescan
**Batch** Current:    1 Total:    2
Blocks Loaded:    0 TrialDecrypted:    0, Witnesses Updated:    0, Total:    1, 
**Batch** Current:    1 Total:    2
Blocks Loaded:    0 TrialDecrypted:    0, Witnesses Updated:    0, Total:    1, 
{
"result": "success",
"latest_block": 2214446,
"total_blocks_synced": 1
}
```
> Switch commands back to returning JSON

- zingolib/Cargo.toml
- zingolib/src/wallet.rs
- zingolib/src/wallet/keys/unified.rs
This unlocks the ability for importing a wallet across FFI that has spending keys, but for which the mnemonic is not known, or perhaps the account index is not the 0 presumed by `WalletBase` when given a mnemonic.
> Initialize wallet with unified spending key

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .editorconfig
- .vscode/extensions.json
- zingo-testutils/src/lib.rs
This ensures that VS Code or GitHub Codespaces can automatically create an environment where `cargo build` and `cargo test` work.
VS Code supports these natively. So long as you have Docker running, it'll create a container and map the git repo you already have into it if you run the "Reopen in devcontainer" command. Then you'll have all the tools necessary to build and test this repo, independent of what you may (not) have available on your regular dev machine.
Codespaces leverage the devcontainer.json but adds value by hosting the container in the cloud for you. [Learn more about GitHub Codespaces](https://docs.github.com/en/codespaces/developing-in-codespaces/developing-in-a-codespace).
This root repo should consider [setting up a …
> Add devcontainer.json

- zingolib/src/wallet.rs
A library should never write to STDOUT of its own accord. It doesn't know what app it's running in and how STDOUT is being used.
We have the zingo-cli and a .NET CLI that I'm writing where this logging was polluting the UX with debugging info.
> Stop writing to STDOUT

- zingolib/src/lightclient.rs
- zingolib/src/wallet.rs
@Oscar-Pepper this is a good start into `zingolib` it's just a refactor that makes `send_to_adresses_inner` less spaghetti-code..
Chopping the spaghetti, I call it.
A critical bit that may be questionable is the new scope (smaller) that the read lock is taken and dropped in.
> Refactor send to address

- zingolib/src/lightclient.rs
- zingolib/src/wallet.rs
This PR, if landed after the ones I opened earlier is _just_ a refactor that properly separates conversion code out of the `send_to_addresses` code (failing before that fn is ever called in the error case).
> Refine tx builder helpers

- zingolib/src/wallet.rs
Hi @juanky201271 the last commit in this PR will change the definition of:
`SendProgressCommand`
link in following comment.
> Update total z recipients

- Cargo.lock
- Cargo.toml
This changes to point at our own fork of `librustzcash` and removes the patch requirement.
We'll need to update our fork to pick up features and bug-fixes from `librustzcash` but...
We:
* won't have to patch
* can easily add our own code the fork
* won't be surprised by movement in librustzcash we didn't explicitly pull in
Interestingly the `zcash_note_encryption` crate *cannot* be referenced via this mechanism...   this may be a bug in up-stream.
> Point at our rc tag

- Cargo.lock
- zingolib/Cargo.toml
This gets zingolib closer to supporting Windows ARM64.
To be fully ready, transitive dependencies on ring 0.16 will have to be updated. All these dependencies have or are working to upgrade, so that should happen soon.
> Bump ring to 0.17.0

- zingolib/src/wallet/keys/extended_transparent.rs
We weren't compliant with bip32 transparent keygen for non-zero account indexes. This shouldn't break anything not belonging to @AArnott, as support for non-zero account indexes landed very recently, hasn't hit release, and I think isn't exposed anywhere other than the library.
> put position in the right place

- .github/workflows/ci.yaml
This PR builds on #601 .
I think we're getting sufficient signal for merge into `dev` from this subset of the tests (provided we're gating merge from `dev` into release more strictly, with e.g. the full 'nightly' test suite).
> Propose fast pr ci

- zingolib/src/blaze/fetch_full_transaction.rs
These messages were printing with "ofthis" and "sentmalicious" appearing at the console.
> Fix missing spaces and punctuation in error message

- zingolib/src/blaze/block_management_reorg_detection.rs
- zingolib/src/blaze/fetch_full_transaction.rs
- zingolib/src/blaze/update_notes.rs
- zingolib/src/error.rs
- zingolib/src/lightclient.rs
- zingolib/src/wallet/transactions.rs
expand error handling to cover the function previously known as mark spent
and standardize search by output index rather than nullifier
> Process Spent Note error handling

- darkside-tests/tests/advanced_reorg_tests.rs
[#620] Advanced ReOrg Test changes outgoing tx height
Closes #620
A Re Org occurs and changes the height of an outbound transaction
Pre-condition: Wallet has funds
Steps:
1. create fake chain
* 1a. sync to latest height
2. send transaction to recipient address
3. getIncomingTransaction
4. stage transaction at `sentTxHeight`
5. applyHeight(sentTxHeight)
6. sync to latest height
* 6a. verify that there's a pending transaction with a mined height of sentTxHeight
7. stage 15  blocks from `sentTxHeight`
7. a stage sent tx to `sentTxHeight + 2`
8. `applyHeight(sentTxHeight + 1)` to cause a 1 block reorg
9. sync to latest height
10. verify that there's a pending transaction with -1 mined height
11. `applyHeight(sentTxHeight + 2)`
* 11a. sync to latest height
12. verify that there's a pending …
> Fixes arot changes outbund tx height

- zingolib/src/lightclient.rs
This is a port from the functionality originally added to Nerdbank.Zcash in [this change](https://github.com/nerdcash/Nerdbank.Cryptocurrencies/pull/150) and subsequently fixed in [this change](https://github.com/nerdcash/Nerdbank.Cryptocurrencies/pull/157).
> Add user balances struct and fn to LightClient

- zingo-testutils/src/regtest.rs
when zingocli is run in regtest mode, expect the specific error naming that ZCASHD must be placed into the correct directory
> improved regtest error msg

- zingocli/Cargo.toml
- zingocli/src/lib.rs
This code adds parsers at the app/command-line boundary:
* birthday --> u32
* server --> http::Uri
* seed --> string of 24 whitespace delimited elements
It also:
* adds deprecations from zingolib, so that the cli will automatically expose "list"
TODO:
* Make cli run without cargo.
* make seed comply with relevant seedphrase-word-library
* remove crufty post-parse code that's no longer necessary
* encode commands.rs as clap subcommands
Tests thus far have been manual invocations of:
```
rm -f ~/wallets/sapling-balance-bug/zingo-wallet.dat && cargo run --bin zingo-cli -- --data-dir ~/wallets/sapling-balance-bug/ --seed "daughter safe REDACTED" --birthday 2328948
```
With various values of the birthday and seed values.  I have not yet tested the server argument.
> Debug clap cli
